apiVersion: v1
entries:
  submariner:
  - apiVersion: v1
    appVersion: 0.6.0
    created: "2022-10-12T22:21:23.818803203Z"
    description: Submariner enables direct networking between Pods and Services in
      different Kubernetes clusters
    digest: 4585cb70dfd75880f0131fc40bc6f637c73d10e6a24ae43a2470e48d1447e0c4
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Submariner Developers
    name: submariner
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-0.7.0.tgz
    version: 0.7.0
  - apiVersion: v1
    appVersion: 0.6.0
    created: "2022-10-12T22:21:23.817480561Z"
    description: Submariner enables direct networking between Pods and Services in
      different Kubernetes clusters
    digest: d54c4d598e68e11deb3683468887b0820637e9dd06379935d5ff3e187836cd91
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Submariner Developers
    name: submariner
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-0.6.0.tgz
    version: 0.6.0
  - apiVersion: v1
    appVersion: 0.4.0
    created: "2022-10-12T22:21:23.816251822Z"
    description: Submariner enables direct networking between Pods and Services in
      different Kubernetes clusters
    digest: e2f11fd1d231b7b1f70274effb471d962bbe7a90383e1213954d3a54af1d4687
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Submariner Developers
    name: submariner
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-0.4.0.tgz
    version: 0.4.0
  - apiVersion: v1
    appVersion: v0.0.4
    created: "2022-10-12T22:21:23.815415096Z"
    description: k8s 1.16.x support
    digest: 6d814e86f82c5e1b7f6c9cd6ed7387b1defd1d56238dfcce654a9b1e2e8042cc
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Submariner Developers
    name: submariner
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-0.0.4.tgz
    version: 0.0.4
  - apiVersion: v1
    appVersion: v0.0.3
    created: "2022-10-12T22:21:23.814407364Z"
    description: k8s 1.16.x support
    digest: 09d528190319d326b65707a2cb87d7f2697e23ac851521f2e156150bc51970db
    home: https://submariner.io/
    maintainers:
    - email: charts@rancher.com
      name: Rancher Labs
    name: submariner
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-0.0.3.tgz
    version: 0.0.3
  - apiVersion: v1
    appVersion: v0.0.2
    created: "2022-10-12T22:21:23.813637339Z"
    description: Submariner with custom ipsec ports support
    digest: e7bdee6dd0b8d84a787e83c112efd948426a991a44529a77bfa36edba9606d8d
    home: https://submariner.io/
    maintainers:
    - email: charts@rancher.com
      name: Rancher Labs
    name: submariner
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-0.0.2.tgz
    version: 0.0.2
  - apiVersion: v1
    appVersion: v0.0.1
    created: "2022-10-12T22:21:23.813001619Z"
    description: Submariner
    digest: 3519f07bb8caa3b3dab5137e3fc7dec4862eb0f306d196d882c0f416033d89df
    home: https://submariner.io/
    maintainers:
    - email: charts@rancher.com
      name: Rancher Labs
    name: submariner
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-0.0.1.tgz
    version: 0.0.1
  submariner-k8s-broker:
  - apiVersion: v2
    appVersion: 0.14.0-m1
    created: "2022-10-12T22:21:23.823859563Z"
    description: Submariner Kubernetes Broker
    digest: fea8b1781211bab2fb8a9638e494664f48bab2ef95293f8e97fa5d0aca5d4259
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Contributors to the Submariner project
      url: https://submariner.io/
    name: submariner-k8s-broker
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-k8s-broker-0.14.0-m1.tgz
    version: 0.14.0-m1
  - apiVersion: v2
    appVersion: 0.13.0-rc2
    created: "2022-10-12T22:21:23.823327946Z"
    description: Submariner Kubernetes Broker
    digest: 5c58412cad1405841ee3d3cff3b0c83d43f3adcf7a988fe8f3e44afc962d4b82
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Contributors to the Submariner project
      url: https://submariner.io/
    name: submariner-k8s-broker
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-k8s-broker-0.13.0-rc2.tgz
    version: 0.13.0-rc2
  - apiVersion: v2
    appVersion: 0.12.2
    created: "2022-10-12T22:21:23.822765929Z"
    description: Submariner Kubernetes Broker
    digest: 95925a3fcc5b66618ccef0e95bde73240a10bcca4644caf34a54c6d645a73362
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Contributors to the Submariner project
      url: https://submariner.io/
    name: submariner-k8s-broker
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-k8s-broker-0.12.2.tgz
    version: 0.12.2
  - apiVersion: v2
    appVersion: 0.6.0
    created: "2022-10-12T22:21:23.822214111Z"
    description: Submariner Kubernetes Broker
    digest: a689b7d0c0fb2bd199c65f163de061bb90fb112ec14ff3b76c889dfce587aaa3
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Contributors to the Submariner project
      url: https://submariner.io/
    name: submariner-k8s-broker
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-k8s-broker-0.11.2.tgz
    version: 0.11.2
  - apiVersion: v2
    appVersion: 0.6.0
    created: "2022-10-12T22:21:23.821694195Z"
    description: Submariner Kubernetes Broker
    digest: 8c21b5e044def3c1593621815ed211eefa990733327c03eefe0051ee0f7cb6e4
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Contributors to the Submariner project
      url: https://submariner.io/
    name: submariner-k8s-broker
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-k8s-broker-0.11.1.tgz
    version: 0.11.1
  - apiVersion: v2
    appVersion: 0.6.0
    created: "2022-10-12T22:21:23.821123377Z"
    description: Submariner Kubernetes Broker
    digest: 96e3a18402db4c4868f489587b3de2b6b9d16239f185df3054f4678f114e742b
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Contributors to the Submariner project
      url: https://submariner.io/
    name: submariner-k8s-broker
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-k8s-broker-0.11.0.tgz
    version: 0.11.0
  - apiVersion: v2
    appVersion: 0.6.0
    created: "2022-10-12T22:21:23.82059516Z"
    description: Submariner Kubernetes Broker
    digest: 4a4133cb9f4f9ac547eb1d2c93afe2ab493af09a7a600cf85fa1e6c5595335e1
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Contributors to the Submariner project
      url: https://submariner.io/
    name: submariner-k8s-broker
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-k8s-broker-0.10.1.tgz
    version: 0.10.1
  - apiVersion: v2
    appVersion: 0.6.0
    created: "2022-10-12T22:21:23.826173537Z"
    description: Submariner Kubernetes Broker
    digest: 63a38cb40f631654994e767c702c1b00d127a7b03feb57ece7d60ac1eeac0c64
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Contributors to the Submariner project
      url: https://submariner.io/
    name: submariner-k8s-broker
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-k8s-broker-0.7.0.tgz
    version: 0.7.0
  - apiVersion: v1
    appVersion: 0.6.0
    created: "2022-10-12T22:21:23.824729791Z"
    description: Submariner Kubernetes Broker
    digest: c18076c7bffa8d9f9ca306894c79975d7a7bb9aa91afc8f3d627b400a7adc768
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Submariner Developers
    name: submariner-k8s-broker
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-k8s-broker-0.6.0.tgz
    version: 0.6.0
  - apiVersion: v1
    appVersion: 0.4.1
    created: "2022-10-12T22:21:23.824250576Z"
    description: Submariner Kubernetes Broker
    digest: a3b99b87d9bd31b20c8faa35e43ea9df4dc369e8ccb05ac6edae93d2242cf8ba
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Submariner Developers
    name: submariner-k8s-broker
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-k8s-broker-0.4.1.tgz
    version: 0.4.1
  - apiVersion: v1
    appVersion: v0.0.2
    created: "2022-10-12T22:21:23.820084544Z"
    description: Submariner Kubernetes Broker
    digest: efc0faba08ed579c6729d02e8d2a5d9826f3bec4119258ae806b30b7625c4150
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Submariner Developers
    name: submariner-k8s-broker
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-k8s-broker-0.0.2.tgz
    version: 0.0.2
  - apiVersion: v1
    appVersion: v0.0.1
    created: "2022-10-12T22:21:23.81934342Z"
    description: Submariner Kubernetes Broker
    digest: a5961dd730ee2c593e86a45c566ce62846fdb1a60b235be4561246d80ec0051e
    home: https://submariner.io/
    maintainers:
    - email: charts@rancher.com
      name: Rancher Labs
    name: submariner-k8s-broker
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-k8s-broker-0.0.1.tgz
    version: 0.0.1
  submariner-operator:
  - apiVersion: v2
    appVersion: 0.14.0-m1
    created: "2022-10-12T22:21:23.8344735Z"
    description: Submariner enables direct networking between Pods and Services in
      different Kubernetes clusters
    digest: 92ee79e392a3421fa86e3fb348c437e64fb6918367ba73a8e03d965ceb4a7a21
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Contributors to the Submariner project
      url: https://submariner.io/
    name: submariner-operator
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-operator-0.14.0-m1.tgz
    version: 0.14.0-m1
  - apiVersion: v2
    appVersion: 0.13.0-rc2
    created: "2022-10-12T22:21:23.833368965Z"
    description: Submariner enables direct networking between Pods and Services in
      different Kubernetes clusters
    digest: 8c29d99b188bee5dc06aadf057f76a4c73a78976303ace8789628ba3f2d57a50
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Contributors to the Submariner project
      url: https://submariner.io/
    name: submariner-operator
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-operator-0.13.0-rc2.tgz
    version: 0.13.0-rc2
  - apiVersion: v2
    appVersion: 0.12.2
    created: "2022-10-12T22:21:23.832361533Z"
    description: Submariner enables direct networking between Pods and Services in
      different Kubernetes clusters
    digest: 9e2c24d33ba9a4ced6b7ab83f35439d9df098f6553c474fcdb29ba32c53c46c5
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Contributors to the Submariner project
      url: https://submariner.io/
    name: submariner-operator
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-operator-0.12.2.tgz
    version: 0.12.2
  - apiVersion: v2
    appVersion: 0.11.2
    created: "2022-10-12T22:21:23.830867385Z"
    description: Submariner enables direct networking between Pods and Services in
      different Kubernetes clusters
    digest: b87a451784561aea6c59ad091cd1c506a1ad17d158c7ddfb7afa5eb6d6916c77
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Contributors to the Submariner project
      url: https://submariner.io/
    name: submariner-operator
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-operator-0.11.2.tgz
    version: 0.11.2
  - apiVersion: v2
    appVersion: 0.11.1
    created: "2022-10-12T22:21:23.829099329Z"
    description: Submariner enables direct networking between Pods and Services in
      different Kubernetes clusters
    digest: 68a10cea87424db5bee1b83487e38f35891c5853a10ad5cc8f181f9a886df6c3
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Contributors to the Submariner project
      url: https://submariner.io/
    name: submariner-operator
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-operator-0.11.1.tgz
    version: 0.11.1
  - apiVersion: v2
    appVersion: 0.11.0
    created: "2022-10-12T22:21:23.828113298Z"
    description: Submariner enables direct networking between Pods and Services in
      different Kubernetes clusters
    digest: 0a8a734997fb8b62429c27b415ff31b51b07d63660b66b2861e768ad70cad88e
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Contributors to the Submariner project
      url: https://submariner.io/
    name: submariner-operator
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-operator-0.11.0.tgz
    version: 0.11.0
  - apiVersion: v2
    appVersion: 0.10.1
    created: "2022-10-12T22:21:23.827150368Z"
    description: Submariner enables direct networking between Pods and Services in
      different Kubernetes clusters
    digest: eaff1f68c6c320a94f9ec0b11a55181a8b548f2d8f5b6bb68a21dcb357ef81df
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Contributors to the Submariner project
      url: https://submariner.io/
    name: submariner-operator
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-operator-0.10.1.tgz
    version: 0.10.1
  - apiVersion: v2
    appVersion: 0.7.0
    created: "2022-10-12T22:21:23.835494232Z"
    description: Submariner enables direct networking between Pods and Services in
      different Kubernetes clusters
    digest: 3213edc4cc0a7bbd5342e46f9671bb2baa56cef65507afe90a812b38da74a2db
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Contributors to the Submariner project
      url: https://submariner.io/
    name: submariner-operator
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-operator-0.7.0.tgz
    version: 0.7.0
generated: "2022-10-12T22:21:23.812123091Z"
