apiVersion: v1
entries:
  submariner:
  - apiVersion: v1
    appVersion: 0.6.0
    created: "2022-08-03T22:29:12.059014931Z"
    description: Submariner enables direct networking between Pods and Services in
      different Kubernetes clusters
    digest: 4585cb70dfd75880f0131fc40bc6f637c73d10e6a24ae43a2470e48d1447e0c4
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Submariner Developers
    name: submariner
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-0.7.0.tgz
    version: 0.7.0
  - apiVersion: v1
    appVersion: 0.6.0
    created: "2022-08-03T22:29:12.058239624Z"
    description: Submariner enables direct networking between Pods and Services in
      different Kubernetes clusters
    digest: d54c4d598e68e11deb3683468887b0820637e9dd06379935d5ff3e187836cd91
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Submariner Developers
    name: submariner
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-0.6.0.tgz
    version: 0.6.0
  - apiVersion: v1
    appVersion: 0.4.0
    created: "2022-08-03T22:29:12.057496317Z"
    description: Submariner enables direct networking between Pods and Services in
      different Kubernetes clusters
    digest: e2f11fd1d231b7b1f70274effb471d962bbe7a90383e1213954d3a54af1d4687
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Submariner Developers
    name: submariner
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-0.4.0.tgz
    version: 0.4.0
  - apiVersion: v1
    appVersion: v0.0.4
    created: "2022-08-03T22:29:12.056786011Z"
    description: k8s 1.16.x support
    digest: 6d814e86f82c5e1b7f6c9cd6ed7387b1defd1d56238dfcce654a9b1e2e8042cc
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Submariner Developers
    name: submariner
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-0.0.4.tgz
    version: 0.0.4
  - apiVersion: v1
    appVersion: v0.0.3
    created: "2022-08-03T22:29:12.056084505Z"
    description: k8s 1.16.x support
    digest: 09d528190319d326b65707a2cb87d7f2697e23ac851521f2e156150bc51970db
    home: https://submariner.io/
    maintainers:
    - email: charts@rancher.com
      name: Rancher Labs
    name: submariner
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-0.0.3.tgz
    version: 0.0.3
  - apiVersion: v1
    appVersion: v0.0.2
    created: "2022-08-03T22:29:12.0554833Z"
    description: Submariner with custom ipsec ports support
    digest: e7bdee6dd0b8d84a787e83c112efd948426a991a44529a77bfa36edba9606d8d
    home: https://submariner.io/
    maintainers:
    - email: charts@rancher.com
      name: Rancher Labs
    name: submariner
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-0.0.2.tgz
    version: 0.0.2
  - apiVersion: v1
    appVersion: v0.0.1
    created: "2022-08-03T22:29:12.054606792Z"
    description: Submariner
    digest: 3519f07bb8caa3b3dab5137e3fc7dec4862eb0f306d196d882c0f416033d89df
    home: https://submariner.io/
    maintainers:
    - email: charts@rancher.com
      name: Rancher Labs
    name: submariner
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-0.0.1.tgz
    version: 0.0.1
  submariner-k8s-broker:
  - apiVersion: v2
    appVersion: 0.13.0-rc2
    created: "2022-08-03T22:29:12.062519962Z"
    description: Submariner Kubernetes Broker
    digest: 9512b9eec238cb4940ea4f8d95e9ea79541bda30f4051e0e1335bb45c2406fab
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Contributors to the Submariner project
      url: https://submariner.io/
    name: submariner-k8s-broker
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-k8s-broker-0.13.0-rc2.tgz
    version: 0.13.0-rc2
  - apiVersion: v2
    appVersion: 0.12.2
    created: "2022-08-03T22:29:12.062114958Z"
    description: Submariner Kubernetes Broker
    digest: 886133b7d7fcc3d1813af0a1b97ab6792c06aa599e2a8a42234e86abeccee5a1
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Contributors to the Submariner project
      url: https://submariner.io/
    name: submariner-k8s-broker
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-k8s-broker-0.12.2.tgz
    version: 0.12.2
  - apiVersion: v2
    appVersion: 0.6.0
    created: "2022-08-03T22:29:12.061125949Z"
    description: Submariner Kubernetes Broker
    digest: a689b7d0c0fb2bd199c65f163de061bb90fb112ec14ff3b76c889dfce587aaa3
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Contributors to the Submariner project
      url: https://submariner.io/
    name: submariner-k8s-broker
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-k8s-broker-0.11.2.tgz
    version: 0.11.2
  - apiVersion: v2
    appVersion: 0.6.0
    created: "2022-08-03T22:29:12.060742346Z"
    description: Submariner Kubernetes Broker
    digest: 8c21b5e044def3c1593621815ed211eefa990733327c03eefe0051ee0f7cb6e4
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Contributors to the Submariner project
      url: https://submariner.io/
    name: submariner-k8s-broker
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-k8s-broker-0.11.1.tgz
    version: 0.11.1
  - apiVersion: v2
    appVersion: 0.6.0
    created: "2022-08-03T22:29:12.060361843Z"
    description: Submariner Kubernetes Broker
    digest: 96e3a18402db4c4868f489587b3de2b6b9d16239f185df3054f4678f114e742b
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Contributors to the Submariner project
      url: https://submariner.io/
    name: submariner-k8s-broker
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-k8s-broker-0.11.0.tgz
    version: 0.11.0
  - apiVersion: v2
    appVersion: 0.6.0
    created: "2022-08-03T22:29:12.059976839Z"
    description: Submariner Kubernetes Broker
    digest: 051114c67310fce8ccda554ae2dad7687f86237253d37aedd1975c67b26329dd
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Contributors to the Submariner project
      url: https://submariner.io/
    name: submariner-k8s-broker
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-k8s-broker-0.10.1.tgz
    version: 0.10.1
  - apiVersion: v2
    appVersion: 0.6.0
    created: "2022-08-03T22:29:12.063972274Z"
    description: Submariner Kubernetes Broker
    digest: 63a38cb40f631654994e767c702c1b00d127a7b03feb57ece7d60ac1eeac0c64
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Contributors to the Submariner project
      url: https://submariner.io/
    name: submariner-k8s-broker
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-k8s-broker-0.7.0.tgz
    version: 0.7.0
  - apiVersion: v1
    appVersion: 0.6.0
    created: "2022-08-03T22:29:12.06351967Z"
    description: Submariner Kubernetes Broker
    digest: c18076c7bffa8d9f9ca306894c79975d7a7bb9aa91afc8f3d627b400a7adc768
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Submariner Developers
    name: submariner-k8s-broker
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-k8s-broker-0.6.0.tgz
    version: 0.6.0
  - apiVersion: v1
    appVersion: 0.4.1
    created: "2022-08-03T22:29:12.063028166Z"
    description: Submariner Kubernetes Broker
    digest: a3b99b87d9bd31b20c8faa35e43ea9df4dc369e8ccb05ac6edae93d2242cf8ba
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Submariner Developers
    name: submariner-k8s-broker
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-k8s-broker-0.4.1.tgz
    version: 0.4.1
  - apiVersion: v1
    appVersion: v0.0.2
    created: "2022-08-03T22:29:12.059598036Z"
    description: Submariner Kubernetes Broker
    digest: efc0faba08ed579c6729d02e8d2a5d9826f3bec4119258ae806b30b7625c4150
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Submariner Developers
    name: submariner-k8s-broker
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-k8s-broker-0.0.2.tgz
    version: 0.0.2
  - apiVersion: v1
    appVersion: v0.0.1
    created: "2022-08-03T22:29:12.059324433Z"
    description: Submariner Kubernetes Broker
    digest: a5961dd730ee2c593e86a45c566ce62846fdb1a60b235be4561246d80ec0051e
    home: https://submariner.io/
    maintainers:
    - email: charts@rancher.com
      name: Rancher Labs
    name: submariner-k8s-broker
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-k8s-broker-0.0.1.tgz
    version: 0.0.1
  submariner-operator:
  - apiVersion: v2
    appVersion: 0.13.0-rc2
    created: "2022-08-03T22:29:12.068881718Z"
    description: Submariner enables direct networking between Pods and Services in
      different Kubernetes clusters
    digest: 58adff60b2a7e47fa4caa33330fdcbc7fbafaf5e43bfd6891eaece49b6b0dba6
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Contributors to the Submariner project
      url: https://submariner.io/
    name: submariner-operator
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-operator-0.13.0-rc2.tgz
    version: 0.13.0-rc2
  - apiVersion: v2
    appVersion: 0.12.2
    created: "2022-08-03T22:29:12.068109711Z"
    description: Submariner enables direct networking between Pods and Services in
      different Kubernetes clusters
    digest: c2db992e3920e22cdfb845511dda7009ef34ffdb167ddc853e96919ba5d64dc0
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Contributors to the Submariner project
      url: https://submariner.io/
    name: submariner-operator
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-operator-0.12.2.tgz
    version: 0.12.2
  - apiVersion: v2
    appVersion: 0.11.2
    created: "2022-08-03T22:29:12.067341404Z"
    description: Submariner enables direct networking between Pods and Services in
      different Kubernetes clusters
    digest: b87a451784561aea6c59ad091cd1c506a1ad17d158c7ddfb7afa5eb6d6916c77
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Contributors to the Submariner project
      url: https://submariner.io/
    name: submariner-operator
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-operator-0.11.2.tgz
    version: 0.11.2
  - apiVersion: v2
    appVersion: 0.11.1
    created: "2022-08-03T22:29:12.066582797Z"
    description: Submariner enables direct networking between Pods and Services in
      different Kubernetes clusters
    digest: 68a10cea87424db5bee1b83487e38f35891c5853a10ad5cc8f181f9a886df6c3
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Contributors to the Submariner project
      url: https://submariner.io/
    name: submariner-operator
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-operator-0.11.1.tgz
    version: 0.11.1
  - apiVersion: v2
    appVersion: 0.11.0
    created: "2022-08-03T22:29:12.06579839Z"
    description: Submariner enables direct networking between Pods and Services in
      different Kubernetes clusters
    digest: 0a8a734997fb8b62429c27b415ff31b51b07d63660b66b2861e768ad70cad88e
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Contributors to the Submariner project
      url: https://submariner.io/
    name: submariner-operator
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-operator-0.11.0.tgz
    version: 0.11.0
  - apiVersion: v2
    appVersion: 0.10.1
    created: "2022-08-03T22:29:12.065036584Z"
    description: Submariner enables direct networking between Pods and Services in
      different Kubernetes clusters
    digest: e363bf5046738373dfdce5850f6163b9044299dd0f93d6c820461285899842b0
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Contributors to the Submariner project
      url: https://submariner.io/
    name: submariner-operator
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-operator-0.10.1.tgz
    version: 0.10.1
  - apiVersion: v2
    appVersion: 0.7.0
    created: "2022-08-03T22:29:12.069589224Z"
    description: Submariner enables direct networking between Pods and Services in
      different Kubernetes clusters
    digest: 3213edc4cc0a7bbd5342e46f9671bb2baa56cef65507afe90a812b38da74a2db
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Contributors to the Submariner project
      url: https://submariner.io/
    name: submariner-operator
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-operator-0.7.0.tgz
    version: 0.7.0
generated: "2022-08-03T22:29:12.05331538Z"
