apiVersion: v1
entries:
  submariner:
  - appVersion: v0.0.2
    created: "2019-11-05T15:25:07.866436761Z"
    description: Submariner with custom ipsec ports support
    digest: e7bdee6dd0b8d84a787e83c112efd948426a991a44529a77bfa36edba9606d8d
    home: https://submariner.io/
    maintainers:
    - email: charts@rancher.com
      name: Rancher Labs
    name: submariner
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-0.0.2.tgz
    version: 0.0.2
  - appVersion: v0.0.1
    created: "2019-11-05T15:25:07.865593558Z"
    description: Submariner
    digest: 3519f07bb8caa3b3dab5137e3fc7dec4862eb0f306d196d882c0f416033d89df
    home: https://submariner.io/
    maintainers:
    - email: charts@rancher.com
      name: Rancher Labs
    name: submariner
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-0.0.1.tgz
    version: 0.0.1
  submariner-k8s-broker:
  - appVersion: v0.0.1
    created: "2019-11-05T15:25:07.867032034Z"
    description: Submariner Kubernetes Broker
    digest: 044504660f28319bb33a5f5636ee7981f144ad3a7b161af32e1570d713150f10
    home: https://submariner.io/
    maintainers:
    - email: charts@rancher.com
      name: Rancher Labs
    name: submariner-k8s-broker
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-k8s-broker-0.0.1.tgz
    version: 0.0.1
generated: "2019-11-05T15:25:07.863815549Z"
