apiVersion: v1
entries:
  submariner:
  - apiVersion: v1
    appVersion: 0.6.0
    created: "2022-10-21T07:57:15.250194651Z"
    description: Submariner enables direct networking between Pods and Services in
      different Kubernetes clusters
    digest: 4585cb70dfd75880f0131fc40bc6f637c73d10e6a24ae43a2470e48d1447e0c4
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Submariner Developers
    name: submariner
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-0.7.0.tgz
    version: 0.7.0
  - apiVersion: v1
    appVersion: 0.6.0
    created: "2022-10-21T07:57:15.24923032Z"
    description: Submariner enables direct networking between Pods and Services in
      different Kubernetes clusters
    digest: d54c4d598e68e11deb3683468887b0820637e9dd06379935d5ff3e187836cd91
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Submariner Developers
    name: submariner
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-0.6.0.tgz
    version: 0.6.0
  - apiVersion: v1
    appVersion: 0.4.0
    created: "2022-10-21T07:57:15.248334292Z"
    description: Submariner enables direct networking between Pods and Services in
      different Kubernetes clusters
    digest: e2f11fd1d231b7b1f70274effb471d962bbe7a90383e1213954d3a54af1d4687
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Submariner Developers
    name: submariner
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-0.4.0.tgz
    version: 0.4.0
  - apiVersion: v1
    appVersion: v0.0.4
    created: "2022-10-21T07:57:15.247464265Z"
    description: k8s 1.16.x support
    digest: 6d814e86f82c5e1b7f6c9cd6ed7387b1defd1d56238dfcce654a9b1e2e8042cc
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Submariner Developers
    name: submariner
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-0.0.4.tgz
    version: 0.0.4
  - apiVersion: v1
    appVersion: v0.0.3
    created: "2022-10-21T07:57:15.246599638Z"
    description: k8s 1.16.x support
    digest: 09d528190319d326b65707a2cb87d7f2697e23ac851521f2e156150bc51970db
    home: https://submariner.io/
    maintainers:
    - email: charts@rancher.com
      name: Rancher Labs
    name: submariner
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-0.0.3.tgz
    version: 0.0.3
  - apiVersion: v1
    appVersion: v0.0.2
    created: "2022-10-21T07:57:15.245805813Z"
    description: Submariner with custom ipsec ports support
    digest: e7bdee6dd0b8d84a787e83c112efd948426a991a44529a77bfa36edba9606d8d
    home: https://submariner.io/
    maintainers:
    - email: charts@rancher.com
      name: Rancher Labs
    name: submariner
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-0.0.2.tgz
    version: 0.0.2
  - apiVersion: v1
    appVersion: v0.0.1
    created: "2022-10-21T07:57:15.244696378Z"
    description: Submariner
    digest: 3519f07bb8caa3b3dab5137e3fc7dec4862eb0f306d196d882c0f416033d89df
    home: https://submariner.io/
    maintainers:
    - email: charts@rancher.com
      name: Rancher Labs
    name: submariner
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-0.0.1.tgz
    version: 0.0.1
  submariner-k8s-broker:
  - apiVersion: v2
    appVersion: 0.14.0-m1
    created: "2022-10-21T07:57:15.255121206Z"
    description: Submariner Kubernetes Broker
    digest: 865c4d9afe6728d821b96c13c591a18989c30537aacd33ca7afed63a30a44517
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Contributors to the Submariner project
      url: https://submariner.io/
    name: submariner-k8s-broker
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-k8s-broker-0.14.0-m1.tgz
    version: 0.14.0-m1
  - apiVersion: v2
    appVersion: 0.13.0-rc2
    created: "2022-10-21T07:57:15.254371382Z"
    description: Submariner Kubernetes Broker
    digest: 5c58412cad1405841ee3d3cff3b0c83d43f3adcf7a988fe8f3e44afc962d4b82
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Contributors to the Submariner project
      url: https://submariner.io/
    name: submariner-k8s-broker
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-k8s-broker-0.13.0-rc2.tgz
    version: 0.13.0-rc2
  - apiVersion: v2
    appVersion: 0.12.2
    created: "2022-10-21T07:57:15.253891467Z"
    description: Submariner Kubernetes Broker
    digest: 416bced2f8d289e8489c845d2933062c429489009630604d92b1283872d887ca
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Contributors to the Submariner project
      url: https://submariner.io/
    name: submariner-k8s-broker
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-k8s-broker-0.12.2.tgz
    version: 0.12.2
  - apiVersion: v2
    appVersion: 0.6.0
    created: "2022-10-21T07:57:15.253436653Z"
    description: Submariner Kubernetes Broker
    digest: a689b7d0c0fb2bd199c65f163de061bb90fb112ec14ff3b76c889dfce587aaa3
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Contributors to the Submariner project
      url: https://submariner.io/
    name: submariner-k8s-broker
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-k8s-broker-0.11.2.tgz
    version: 0.11.2
  - apiVersion: v2
    appVersion: 0.6.0
    created: "2022-10-21T07:57:15.252945537Z"
    description: Submariner Kubernetes Broker
    digest: 8c21b5e044def3c1593621815ed211eefa990733327c03eefe0051ee0f7cb6e4
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Contributors to the Submariner project
      url: https://submariner.io/
    name: submariner-k8s-broker
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-k8s-broker-0.11.1.tgz
    version: 0.11.1
  - apiVersion: v2
    appVersion: 0.6.0
    created: "2022-10-21T07:57:15.252480923Z"
    description: Submariner Kubernetes Broker
    digest: 96e3a18402db4c4868f489587b3de2b6b9d16239f185df3054f4678f114e742b
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Contributors to the Submariner project
      url: https://submariner.io/
    name: submariner-k8s-broker
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-k8s-broker-0.11.0.tgz
    version: 0.11.0
  - apiVersion: v2
    appVersion: 0.6.0
    created: "2022-10-21T07:57:15.251391188Z"
    description: Submariner Kubernetes Broker
    digest: a19c9d478c234c06f6b3bf75ff077a5d02663af936b0ab48c98b4ede9ec12080
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Contributors to the Submariner project
      url: https://submariner.io/
    name: submariner-k8s-broker
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-k8s-broker-0.10.1.tgz
    version: 0.10.1
  - apiVersion: v2
    appVersion: 0.6.0
    created: "2022-10-21T07:57:15.256729256Z"
    description: Submariner Kubernetes Broker
    digest: 63a38cb40f631654994e767c702c1b00d127a7b03feb57ece7d60ac1eeac0c64
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Contributors to the Submariner project
      url: https://submariner.io/
    name: submariner-k8s-broker
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-k8s-broker-0.7.0.tgz
    version: 0.7.0
  - apiVersion: v1
    appVersion: 0.6.0
    created: "2022-10-21T07:57:15.256191539Z"
    description: Submariner Kubernetes Broker
    digest: c18076c7bffa8d9f9ca306894c79975d7a7bb9aa91afc8f3d627b400a7adc768
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Submariner Developers
    name: submariner-k8s-broker
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-k8s-broker-0.6.0.tgz
    version: 0.6.0
  - apiVersion: v1
    appVersion: 0.4.1
    created: "2022-10-21T07:57:15.255668723Z"
    description: Submariner Kubernetes Broker
    digest: a3b99b87d9bd31b20c8faa35e43ea9df4dc369e8ccb05ac6edae93d2242cf8ba
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Submariner Developers
    name: submariner-k8s-broker
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-k8s-broker-0.4.1.tgz
    version: 0.4.1
  - apiVersion: v1
    appVersion: v0.0.2
    created: "2022-10-21T07:57:15.250897273Z"
    description: Submariner Kubernetes Broker
    digest: efc0faba08ed579c6729d02e8d2a5d9826f3bec4119258ae806b30b7625c4150
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Submariner Developers
    name: submariner-k8s-broker
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-k8s-broker-0.0.2.tgz
    version: 0.0.2
  - apiVersion: v1
    appVersion: v0.0.1
    created: "2022-10-21T07:57:15.250556262Z"
    description: Submariner Kubernetes Broker
    digest: a5961dd730ee2c593e86a45c566ce62846fdb1a60b235be4561246d80ec0051e
    home: https://submariner.io/
    maintainers:
    - email: charts@rancher.com
      name: Rancher Labs
    name: submariner-k8s-broker
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-k8s-broker-0.0.1.tgz
    version: 0.0.1
  submariner-operator:
  - apiVersion: v2
    appVersion: 0.14.0-m1
    created: "2022-10-21T07:57:15.263782778Z"
    description: Submariner enables direct networking between Pods and Services in
      different Kubernetes clusters
    digest: e09c3f393de3ef3dcf9060dd6df6af6f2e53b3d908bb1886a23a12b26bf74a4f
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Contributors to the Submariner project
      url: https://submariner.io/
    name: submariner-operator
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-operator-0.14.0-m1.tgz
    version: 0.14.0-m1
  - apiVersion: v2
    appVersion: 0.13.0-rc2
    created: "2022-10-21T07:57:15.262784047Z"
    description: Submariner enables direct networking between Pods and Services in
      different Kubernetes clusters
    digest: 8c29d99b188bee5dc06aadf057f76a4c73a78976303ace8789628ba3f2d57a50
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Contributors to the Submariner project
      url: https://submariner.io/
    name: submariner-operator
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-operator-0.13.0-rc2.tgz
    version: 0.13.0-rc2
  - apiVersion: v2
    appVersion: 0.12.2
    created: "2022-10-21T07:57:15.261844817Z"
    description: Submariner enables direct networking between Pods and Services in
      different Kubernetes clusters
    digest: f6e1431f4811fa018e8ec985e03b14c0e08aab0b7e38fb4050b19198623223f7
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Contributors to the Submariner project
      url: https://submariner.io/
    name: submariner-operator
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-operator-0.12.2.tgz
    version: 0.12.2
  - apiVersion: v2
    appVersion: 0.11.2
    created: "2022-10-21T07:57:15.260894087Z"
    description: Submariner enables direct networking between Pods and Services in
      different Kubernetes clusters
    digest: b87a451784561aea6c59ad091cd1c506a1ad17d158c7ddfb7afa5eb6d6916c77
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Contributors to the Submariner project
      url: https://submariner.io/
    name: submariner-operator
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-operator-0.11.2.tgz
    version: 0.11.2
  - apiVersion: v2
    appVersion: 0.11.1
    created: "2022-10-21T07:57:15.259984358Z"
    description: Submariner enables direct networking between Pods and Services in
      different Kubernetes clusters
    digest: 68a10cea87424db5bee1b83487e38f35891c5853a10ad5cc8f181f9a886df6c3
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Contributors to the Submariner project
      url: https://submariner.io/
    name: submariner-operator
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-operator-0.11.1.tgz
    version: 0.11.1
  - apiVersion: v2
    appVersion: 0.11.0
    created: "2022-10-21T07:57:15.259039129Z"
    description: Submariner enables direct networking between Pods and Services in
      different Kubernetes clusters
    digest: 0a8a734997fb8b62429c27b415ff31b51b07d63660b66b2861e768ad70cad88e
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Contributors to the Submariner project
      url: https://submariner.io/
    name: submariner-operator
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-operator-0.11.0.tgz
    version: 0.11.0
  - apiVersion: v2
    appVersion: 0.10.1
    created: "2022-10-21T07:57:15.258084299Z"
    description: Submariner enables direct networking between Pods and Services in
      different Kubernetes clusters
    digest: e9a5e8e7e3bfe76e13018ad9b456fb0cb0f5c1f66af1ab214348ba31424732ca
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Contributors to the Submariner project
      url: https://submariner.io/
    name: submariner-operator
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-operator-0.10.1.tgz
    version: 0.10.1
  - apiVersion: v2
    appVersion: 0.7.0
    created: "2022-10-21T07:57:15.264643705Z"
    description: Submariner enables direct networking between Pods and Services in
      different Kubernetes clusters
    digest: 3213edc4cc0a7bbd5342e46f9671bb2baa56cef65507afe90a812b38da74a2db
    home: https://submariner-io.github.io/
    maintainers:
    - email: submariner-dev@googlegroups.com
      name: Contributors to the Submariner project
      url: https://submariner.io/
    name: submariner-operator
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-operator-0.7.0.tgz
    version: 0.7.0
generated: "2022-10-21T07:57:15.243595743Z"
