apiVersion: v1
entries:
  submariner:
  - appVersion: v0.0.2
    created: "2019-09-27T12:20:10.442287061Z"
    description: Submariner with custom ipsec ports support
    digest: a664dd7f1e1a210c80f147f0dcdf0f99ed737cca1818143aecf5160e6a5068f2
    home: https://submariner.io/
    maintainers:
    - email: charts@rancher.com
      name: Rancher Labs
    name: submariner
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-0.0.2.tgz
    version: 0.0.2
  - appVersion: v0.0.1
    created: "2019-09-27T12:20:10.441485121Z"
    description: Submariner
    digest: 3519f07bb8caa3b3dab5137e3fc7dec4862eb0f306d196d882c0f416033d89df
    home: https://submariner.io/
    maintainers:
    - email: charts@rancher.com
      name: Rancher Labs
    name: submariner
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-0.0.1.tgz
    version: 0.0.1
  submariner-k8s-broker:
  - appVersion: v0.0.1
    created: "2019-09-27T12:20:10.442857088Z"
    description: Submariner Kubernetes Broker
    digest: 9d890c8d8d81cebbeb741c3336811c793d229e0b890cf78f0659e29f3b305386
    home: https://submariner.io/
    maintainers:
    - email: charts@rancher.com
      name: Rancher Labs
    name: submariner-k8s-broker
    sources:
    - https://submariner-io.github.io/submariner-charts/charts
    urls:
    - https://submariner-io.github.io/submariner-charts/charts/submariner-k8s-broker-0.0.1.tgz
    version: 0.0.1
generated: "2019-09-27T12:20:10.440230608Z"
